** Paquete ~nacal~ para usar la notación del curso de Álgebra Lineal (y Econometría) en documentos escritos con de $\LaTeX{.}$

~nacal~ es un paquete de $\LaTeX{}$ con las macros que diseñé al
escribir el [[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]] para el curso de Álgebra Lineal del [[https://www.ucm.es/estudios/grado-economia][Grado en
Economía]] de la [[https://www.ucm.es/][UCM]].

Cualquier error o sugerencia correspondiente al paquete nacal.sty debe
ser enviada a:

Marcos Bujosa (mbujosab@ucm.es) o indicada como un [[https://github.com/mbujosab/CursoDeAlgebraLineal/issues][issue]].

El libro de Álgebra Lineal se puede descargar desde
[[https://github.com/mbujosab/CursoDeAlgebraLineal]].


*** Historia
Al escribir el [[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]] generé un sencillo fichero con la definición de
las macros. Dicho fichero era leído desde el preámbulo del fichero
fuente del libro (así como desde el preámbulo del resto del materiales
generados para mis clases).

Tras escribir el libro he intentado generar preguntas de opción
múltiple para ser usadas desde [[https://moodle.com/solutions/lms/][Moodle]], pero he encontrado dificultades
para reproducir la misma notación usada en el [[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]]. Haciendo una
búsqueda por internet encontré el repositorio
[[https://github.com/alephsub0/LaTeX_aleph-moodle]] (de Jonathan Ortiz y
Andrés Merino) que me dio la pista de cómo lograr reproducir la
notación del libro mediante el uso del paquete [[https://ctan.org/pkg/moodle][moodle.sty]] de Anders
Hendrickson y Matthieu Guerquin-Kern.

Al igual que hicieron Jonathan Ortiz y Andrés Merino, he creado dos
paquetes. El paquete [[https://github.com/mbujosab/nacal-latex-package][nacal.sty]] (de este repositorio) contiene las
macros del fichero original empleado en el libro. El paquete
nacal-moodle.sty (en otro repositorio) indica al paquete [[https://ctan.org/pkg/moodle][moodle.sty]]
cómo pintar los símbolos en los ficheros ~.xml~ que [[https://moodle.com/solutions/lms/][Moodle]] emplea en
sus bancos de preguntas.

Si solo necesita emplear la misma notación del [[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]] es sus documentos
de $\LaTeX{}$, basta con el paquete [[https://github.com/mbujosab/nacal-latex-package][nacal.sty]] de este repositorio. Si
también desea generar bancos de preguntas para [[https://moodle.com/solutions/lms/][Moodle]], entonces
también necesitará nacal-moodle.sty.

*** Instalación

Como cualquier paquete de $\LaTeX{}$, para crear debe incluir
nacal.sty en el directorio de trabajo (o allí donde su instalación de
$\LaTeX{}$ busque los paquetes), y en el preámbulo de su documento
debe incluir ~\usepackage{nacal}~

Para obtener el fichero ~nacal.sty~ debe ejecutar ~latex nacal.ins~ y
para compilar la documentación ~pdflatex nacal.dtx~.


**** Licencia del paquete nacal.sty

Este archivo puede ser distribuido y/o modificado bajo las condiciones
de la Licencia Pública del Proyecto LaTeX, ya sea la versión 1.3 de
esta licencia o (a su elección) cualquier versión posterior. La última
versión de esta licencia está en:

http://www.latex-project.org/lppl.txt

y la versión 1.3 o posterior es parte de las distribuciones de
LaTeX con versión 2005/12/01 o posteriores.
