** Paquete de \LaTeX{} para usar la notación del curso de Álgebra Lineal (y Econometría)
Este es un proyecto para generar un paquete de \LaTeX{} con las macros
que diseñé al escribir el [[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]] para el curso de Álgebra Lineal del
[[https://www.ucm.es/estudios/grado-economia][Grado en Economía]] de la [[https://www.ucm.es/][UCM]].

Cualquier error o sugerencia correspondiente al paquete nacal.sty debe
ser enviada a:

Marcos Bujosa (mbujosab@ucm.es) o indicada como un [[https://github.com/mbujosab/CursoDeAlgebraLineal/issues][issue]].

El libro de Álgebra Lineal se puede descargar desde
[[https://github.com/mbujosab/CursoDeAlgebraLineal]].


*** Historia

Inicialmente generé un sencillo fichero con la definición de las
macros. Dicho fichero era leído desde el preámbulo del fichero fuente
del libro (así como con el resto del materiales generados para mis
clases).

Tras escribir el libro he intentado generar algunas preguntas de
opción múltiple para ser usadas desde [[https://moodle.com/solutions/lms/][Moodle]], pero he encontrado
dificultades para reproducir la misma notación usada en el
[[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]]. Haciendo una búsqueda por internet encontré el siguiente
repositorio de Jonathan Ortiz y Andrés Merino

[[https://github.com/alephsub0/LaTeX_aleph-moodle]]

que me dio la pista de cómo lograr reproducir la notación del libro
mediante el uso del paquete [[https://ctan.org/pkg/moodle][moodle.sty]] de Anders Hendrickson y
Matthieu Guerquin-Kern. Al igual que hicieron Jonathan Ortiz y Andrés
Merino, he creado dos paquetes. El paquete nacal.sty (de este
repositorio) reproduce las macros del libro, y el paquete
nacal-moodle.sty (en otro repositorio) indica al paquete [[https://ctan.org/pkg/moodle][moodle.sty]]
cómo pintar los símbolos en los ficheros ~.xml~ que [[https://moodle.com/solutions/lms/][Moodle]] emplea en
sus bancos de preguntas.

Si tan solo quiere escribir con \LaTeX{} empleando la misma notación
del [[https://github.com/mbujosab/CursoDeAlgebraLineal/blob/master/libro.pdf][libro]], basta con el paquete nacal.sty de este repositorio. Si
desea generar bancos de preguntas para [[https://moodle.com/solutions/lms/][Moodle]], entonces también
necesitará nacal-moodle.sty.

*** Instalación

Como cualquier paquete de \LaTeX{}, para crear debe incluir nacal.sty
en el directorio de trabajo (o allí donde su instalación de \LaTeX{}
busque los paquetes), y en el preámbulo de su documento debe incluir
~\usepackage{nacal}~

Para obtener el fichero ~nacal.sty~ debe ejecutar ~latex nacal.ins~ y
para compilar la documentación ~pdflatex nacal.dtx~.


**** Licencia del paquete nacal.sty

Este archivo puede ser distribuido y/o modificado bajo las condiciones
de la Licencia Pública del Proyecto LaTeX, ya sea la versión 1.3 de
esta licencia o (a su elección) cualquier versión posterior. La última
versión de esta licencia está en:

http://www.latex-project.org/lppl.txt

y la versión 1.3 o posterior es parte de las distribuciones de
LaTeX con versión 2005/12/01 o posteriores.
